# Generated by Django 3.0.6 on 2020-05-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_appi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('topi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_appi.topic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
