# Generated by Django 3.0.6 on 2020-08-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_appi', '0016_auto_20200807_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic_c',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_appi.Topic'),
        ),
    ]
